openapi: 3.0.0
info:
  title: Voucher API
  version: '1.0'
  description: Myriad Voucher Endpoints
  contact:
    email: lzhang@udap.io
  license:
    name: MIT
    url: 'https://tldrlegal.com/license/mit-license'
servers:
  - url: 'https://voucherapi-test.chainmind.io'
paths:
  /vouchers:
    get:
      summary: Query vouchers
      tags:
        - Voucher
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedVoucherResponse'
              examples:
                example-1:
                  value:
                    total: 1
                    page: 0
                    size: 20
                    entries:
                      - id: 4a29e8b8-fd53-42b7-8df5-5fb663fe1370
                        code: '13455914'
                        effective: '2020-05-01'
                        expiry: '2020-06-01'
                        status: ACTIVE
                        merchantCount: 1
                        config:
                          type: COUPON
                          description: 'anything about the voucher, e.g., redemption instructions'
                          redemption: 1
                          discount:
                            type: AMOUNT
                            valueOff: 500
                      - id: 2bf8ff3f-96a3-4a19-9ad7-9d308b8ada11
                        code: '59348865'
                        effective: '2020-05-01'
                        expiry: '2020-06-01'
                        status: ACTIVE
                        merchantCount: 5
                        config:
                          type: COUPON
                          description: 'anything about the voucher, e.g., redemption instructions'
                          redemption: 1
                          discount:
                            type: AMOUNT
                            valueOff: 500
      description: Query vouchers of a user with given status that can be redeemed at the given merchant or any merchant.
      parameters:
        - schema:
            type: string
            enum: []
          in: query
          name: ownerId
          description: id of the owner of the returned vouchers
          required: true
        - schema:
            type: string
            enum:
              - REDEEMED
              - ACTIVE
              - EXPIRED
              - PENDING
          in: query
          name: status
          description: voucher status
        - schema:
            type: string
          in: query
          name: merchantCode
          description: Identifier of the merchant where vouchers can be redeemed
        - schema:
            type: integer
            default: '0'
          in: query
          name: page
          description: 'page ordinal number, default to 0'
        - schema:
            type: integer
            default: '20'
          in: query
          name: size
          description: 'max number of vouchers returned from the query, default to 20'
        - schema:
            type: string
            enum:
              - ID
              - CELLPHONE
          in: query
          name: idType
          description: 'owner ID type, default to ID'
        - schema:
            type: string
            enum:
              - ID
              - LICENSE
              - UPCODE
          in: query
          name: codeType
          description: 'merchant code type, default to ID'
      operationId: get-vouchers
  /redemptions:
    put:
      summary: Confirm a redemption
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ConfirmRedemptionResponse'
        '404':
          description: Voucher Not Found or Not Redeemed Yet
      description: Confirm the success or failure of a previous  redemption
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ConfirmRedemptionRequest'
        description: ''
      operationId: confirm-redemption
      tags:
        - Redemption
    post:
      summary: Create a redemption
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateRedemptionResponse'
        '404':
          description: Voucher Not Found
        '409':
          description: Voucher Status Conflict
      description: Create a redemption to redeem a voucher
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateRedemptionRequest'
        description: CreateRedemptionRequest
      operationId: create-redemption
      tags:
        - Redemption
  /merchants:
    get:
      summary: Query merchants
      tags:
        - Merchant
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedMerchantResponse'
      description: Query merchants created after the specified date parameter
      parameters:
        - schema:
            type: string
            pattern: YYYY-MM-DD
          in: query
          name: createdAfter
          description: a param used to query merchants created after this given date
          required: true
      operationId: get-merchants
  '/merchants/{code}':
    parameters:
      - schema:
          type: string
        name: code
        in: path
        required: true
        description: code used to identify a merchant
    get:
      summary: Query a merchant by code
      tags:
        - Merchant
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Merchant'
        '404':
          description: Not Found
      parameters:
        - schema:
            type: string
            enum:
              - ID
              - LICENSE
              - YCODE
          in: query
          name: codeType
          description: code type; default to ID if not present
      description: Query a merchant given its code and code type
      operationId: get-merchant-by-code
  '/users/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: used to uniquely identify a user
    get:
      summary: Query a user by code
      tags:
        - User
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: Not Found
      parameters:
        - schema:
            type: string
            enum:
              - ID
              - CELLPHONE
          in: query
          name: idType
          description: 'id type, default to ID'
      description: Query a user by id and id type
      operationId: get-user-by-id
  '/vouchers/{id}':
    parameters:
      - schema:
          type: string
        name: id
        in: path
        required: true
        description: voucher identifier
    get:
      summary: Query a voucher by id
      tags:
        - Voucher
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Voucher'
              examples:
                example-1:
                  value:
                    id: 4a29e8b8-fd53-42b7-8df5-5fb663fe1370
                    issuer: 重庆农商行
                    code: '13455914'
                    effective: '2020-05-01'
                    expiry: '2020-06-01'
                    status: ACTIVE
                    redeemedQuantity: 0
                    config:
                      type: COUPON
                      description: 'anything about the voucher, e.g., redemption instructions'
                      redemption: 1
                      discount:
                        type: AMOUNT
                        valueOff: 500
        '404':
          description: Voucher Not Found
      description: Query a voucher given its identifier
      operationId: get-voucher-by-id
  /vouchers/batchTransfer:
    post:
      summary: Batch Transfer Vouchers
      operationId: post-vouchers-batchTransfer
      responses:
        '200':
          description: OK
      description: Batch transfer vouchers
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BatchTransferRequest'
            examples:
              example-1:
                value:
                  campaignId: 6e697b7a-0a42-400a-9e33-06f7dec94934
                  reqUser: '121263'
                  entries:
                    - fromOwner: '121263'
                      toOwner: '1722'
                      amount: 100
                    - fromOwner: '121263'
                      toOwner: '917'
                      amount: 50
components:
  schemas:
    PaginatedVoucherResponse:
      title: PaginatedVoucherResponse
      type: object
      x-tags:
        - Voucher
      properties:
        total:
          type: integer
          description: total number of pages
        page:
          type: integer
          description: current page
        size:
          type: integer
          description: size of the page
        entries:
          description: a list of VoucherListItem
          type: array
          items:
            $ref: '#/components/schemas/VoucherListItem'
      required:
        - total
        - page
        - size
        - entries
    VoucherListItem:
      title: VoucherListItem
      type: object
      properties:
        id:
          type: string
          description: voucher identifier
        code:
          type: string
          description: voucher code
        category:
          type: string
          description: voucher category
        effective:
          type: string
          format: date
          description: effective date
        expiry:
          type: string
          format: date
          description: expiry date
        status:
          type: string
          description: voucher status
          enum:
            - REDEEMED
            - ACTIVE
            - EXPIRED
            - PENDING
        config:
          $ref: '#/components/schemas/VoucherConfig'
        campaign:
          $ref: '#/components/schemas/Campaign'
        merchantCount:
          type: integer
          description: number of merchants where the voucher can be redeemed
      required:
        - id
        - code
        - effective
        - expiry
        - status
        - config
        - merchantCount
    VoucherConfig:
      title: VoucherConfig
      type: object
      x-tags:
        - Voucher
      description: Voucher configuraiton. A voucher config is usually shared by a set of vouchers of a voucher campaign.
      properties:
        code:
          type: string
          description: code for fixed voucher
        description:
          type: string
          description: description such as redemption instructions or anything you want to the customer to read
        authorizationRequired:
          type: boolean
          description: does the voucher require additional authorization for redemption
        discount:
          $ref: '#/components/schemas/Discount'
        coverImg:
          type: string
          description: voucher cover image url
        type:
          type: string
          description: 'voucher type, e.g. COUPON'
          enum:
            - COUPON
        redemption:
          type: integer
          default: 1
          description: maximum redemptions
      required:
        - discount
        - type
        - redemption
    Discount:
      title: Discount
      type: object
      x-tags:
        - Voucher
      x-examples:
        $20 off:
          type: AMOUNT
          valueOff: 2000
        '15% off':
          type: PERCENT
          valueOff: 15
      properties:
        type:
          type: string
          description: discount type
          enum:
            - AMOUNT
            - PERCENT
        valueOff:
          type: integer
          description: 'amount off in cents (e.g, 2000 represent 20 RMB off the original price) or percentage off (e.g, 20 represents 20% off the original price)'
        amountLimit:
          type: integer
          description: maximum discount amount in cent when type is PERCENT
      required:
        - type
        - valueOff
    CreateRedemptionRequest:
      title: CreateRedemptionRequest
      type: object
      x-examples:
        example-1:
          value:
            voucherId: ffed7134-797a-4d87-a58c-a8de6a5c212e
            reqUserId: '18621998888'
            idType: CELLPHONE
            merchantCode: 91310000MA1GUUWC0X
            codeType: LICENSE
            orderId: '9001000001'
      x-tags:
        - Redemption
      properties:
        voucherId:
          type: string
          description: identifier of the voucher to be redeemed
        reqUserId:
          type: string
          description: the user that redeems the voucher
        merchantCode:
          type: string
          description: identifier of the merchant that executes the redemption
        orderId:
          type: string
          description: identifier of the order that the voucher is applied to
        codeType:
          type: string
          default: ID
          description: merchant code type
          enum:
            - ID
            - LICENSE
            - YCODE
        idType:
          type: string
          default: ID
          description: user id type
          enum:
            - ID
            - CELLPHONE
      required:
        - voucherId
        - reqUserId
        - merchantCode
        - orderId
    ConfirmRedemptionRequest:
      title: ConfirmRedemptionRequest
      type: object
      x-examples:
        example-1:
          value:
            voucherId: ffed7134-797a-4d87-a58c-a8de6a5c212e
            merchantCode: 91310000MA1GUUWC0X
            codeType: LICENSE
            orderId: '9001000001'
            status: SUCCESS
      x-tags:
        - Redemption
      properties:
        voucherId:
          type: string
          description: identifier of the voucher that was redeemed
        merchantCode:
          type: string
          description: identifier of the merchant that accepted the voucher
        orderId:
          type: string
          description: order that the redemption was applied to
        status:
          type: string
          description: redemption status
          enum:
            - SUCCESS
            - FAILED
        codeType:
          type: string
          default: ID
          description: merchant code type
          enum:
            - ID
            - LICENSE
            - YCODE
      required:
        - voucherId
        - merchantCode
        - orderId
        - status
    CreateRedemptionResponse:
      title: CreateRedemptionResponse
      type: object
      properties:
        id:
          type: string
          description: redemption id
        createdAt:
          type: string
          format: date-time
          description: the timestamp that this redemption was created
        createdBy:
          type: string
          description: the user who executed the redemption
        status:
          type: string
          description: the status of the redemption
          enum:
            - PENDING
            - SUCCESS
            - FAILED
      required:
        - id
        - createdAt
        - createdBy
        - status
      x-tags:
        - Redemption
    ConfirmRedemptionResponse:
      title: ConfirmRedemptionResponse
      type: object
      properties:
        id:
          type: string
          description: the redemption id
        voucherId:
          type: string
          description: the voucher that was redeemed
        status:
          type: string
          description: redemption status
          enum:
            - SUCCESS
            - FAILED
      required:
        - id
        - voucherId
        - status
      x-tags:
        - Redemption
    MerchantListItem:
      title: PaginatedMerchantResponse
      type: object
      x-tags:
        - Merchant
      properties:
        id:
          type: string
          description: merchant identifier
        name:
          type: string
          description: merchant full name
        shortName:
          type: string
          description: merchant short name
        address:
          type: string
          description: address of the merchant
        phone:
          type: string
          description: contact phone
      required:
        - id
        - name
    PaginatedMerchantResponse:
      title: PaginatedMerchantResponse
      type: object
      properties:
        total:
          type: integer
          description: total number of pages
        page:
          type: integer
          description: current page
        size:
          type: integer
          description: page size
        entries:
          type: array
          items:
            $ref: '#/components/schemas/MerchantListItem'
      required:
        - total
        - page
        - size
      x-tags:
        - Merchant
    Merchant:
      title: Merchant
      type: object
      properties:
        id:
          type: string
          description: merchant identifier
        name:
          type: string
          description: name of the merchant
        shortName:
          type: string
          description: short name of the merchant
        code:
          type: string
          description: code of the merchant
        licenseNo:
          type: string
          description: business license number
        phone:
          type: string
          description: contact phone number
        streetAddress:
          type: string
          description: street address
        district:
          type: string
          description: district
        city:
          type: string
          description: city
        province:
          type: string
          description: province
        postalCode:
          type: string
          description: postal code
      required:
        - id
        - name
        - licenseNo
        - phone
        - streetAddress
        - city
        - province
      x-tags:
        - Merchant
    User:
      title: User
      type: object
      properties:
        id:
          type: string
          description: user identifier
        cellphone:
          type: string
          description: "user's cellphone number"
      required:
        - id
        - cellphone
      x-tags:
        - User
    Voucher:
      title: Voucher
      type: object
      x-tags:
        - Voucher
      properties:
        id:
          type: string
          description: voucher identifier
        issuer:
          type: string
          description: the issuer id
        code:
          type: string
          description: voucher code
        category:
          type: string
          description: voucher category
        effective:
          type: string
          description: voucher effective date
          format: date
        expiry:
          type: string
          description: voucher expiry date
          format: date
        status:
          type: string
          description: voucher status
          enum:
            - REDEEMED
            - ACTIVE
            - EXPIRED
            - PENDING
        redeemedQuantity:
          type: integer
          description: redeemed count
        config:
          $ref: '#/components/schemas/VoucherConfig'
        campaign:
          $ref: '#/components/schemas/Campaign'
        merchants:
          type: array
          items:
            $ref: '#/components/schemas/MerchantListItem'
      required:
        - id
        - issuer
        - code
        - effective
        - expiry
        - status
        - redeemedQuantity
        - config
    Campaign:
      title: Campaign
      type: object
      properties:
        id:
          type: string
          description: campaign id
        name:
          type: string
          description: campaign name
      required:
        - id
        - name
    TransferDestination:
      title: TransferDestination
      type: object
      description: Transfer destination of a batch transfer operation
      properties:
        fromOwner:
          type: string
        toOwner:
          type: string
        amount:
          type: integer
          minimum: 1
      required:
        - fromOwner
        - toOwner
        - amount
    BatchTransferRequest:
      title: BatchTransferRequest
      type: object
      description: Batch transfer request
      properties:
        campaignId:
          type: string
          description: campaign id
        reqUser:
          type: string
          description: request user id
        entries:
          type: array
          description: transfer definitions
          minItems: 1
          items:
            $ref: '#/components/schemas/TransferDef'
      required:
        - campaignId
        - reqUser
        - entries
